package pl.codeleak.demos.sbt.enumeradores;

public enum Categoria {

    ALMACEN, HELADOS, CIGARRILLOS, GOLOSINAS,
    BEBIDAS, VINOS, CERVEZAS, ELECTRONICA, MEDICAMENTOS, LACTEOS,
    PASTAS, HIGIENE, COMIDA, SNACK, GALLETITAS, PANADERIA, ENVASES, DEPOSITOS, SUELDOS, ADMINISTRATIVOS
}
